### PR TITLE
Allow local dtm from m2l.Project constructor

### PR DESCRIPTION
**Pull request by T4mmi**
Hi all,

This PR offers a quick solution to provide your own DTM as a GeoTiff file without any `m2l` code changes.
It adds a parameter `dtm_file` to the `Project()` constructor wich points to the local geotiff.
If `FileNotFound` it should switch to opentopography web request (REST API) already coded ...

TODO: allow to pass any OGC compliant URL ...

_I don't know if you have a 'develop' branch with CI to test if it doesn't break your notebooks examples, we tried it locally it seems to work with our data and current notebooks ... but ..._

### CODE REVIEW

**Comment by T4mmi** [comment]
Also, maybe we could add a mapper of services based on country code (instead of state code ?) to recover accurate DTM and/or switch to opentopo whenever it fails (with warnings)...

**Review by yohanderose — APPROVED** [review]
Looks good, will pull and start testing

**Comment by markjessell** [comment]
Could also look at using at https://pypi.org/project/elevation/ as a source of data (although it doesn't like large areas to be selected)

m

**Comment by T4mmi** [comment]
We are testing it and it should work with a local dtm file (geotiff), we should try the opentopo request today, I'll look into `elevation` !

but when outside AU we have problems further in the code (we are investigating how to soften pieces of hard code)

**Pull request merged**
